protohaven/protohaven_api

protohaven_api/class_automation/scheduler.py, protohaven_api/class_automation/scheduler_test.py, protohaven_api/config.py, protohaven_api/integrations/airtable.py, protohaven_api/integrations/airtable_test.py, protohaven_api/integrations/tasks.py, protohaven_api/testing.py, requirements.txt
Fixes DST issue in instructor calendar.
Required reading: https://blog.ganssle.io/articles/2018/03/pytz-fastest-footgun.html
Also fix generator materialization issue in add_maintenance_task_if_not_exists().
=> Switch from eager time zone evaluation via pytz to correct dateutil.tz

.env.default, config.yaml, protohaven_api/app.py, protohaven_api/automation/membership/sign_in_test.py, protohaven_api/handlers/admin_test.py, protohaven_api/handlers/index_test.py, protohaven_api/handlers/instructor_test.py, protohaven_api/handlers/onboarding_test.py, protohaven_api/handlers/techs.py, protohaven_api/handlers/techs_test.py, protohaven_api/integrations/comms_test.py, protohaven_api/integrations/templates/class_proposals.jinja2, protohaven_api/integrations/templates/instructor_applications.jinja2, protohaven_api/integrations/templates/shop_tech_applications.jinja2, protohaven_api/integrations/templates/tech_leads_maintenance_status.jinja2, protohaven_api/integrations/templates/tech_openings.jinja2, protohaven_api/main.py, protohaven_api/passenger_wsgi.py, protohaven_api/scripts/run_command.sh, protohaven_api/testing.py, svelte/src/lib/techs/events.svelte
Also fixed session/role testing in tests that used flask's `test_client`, and cleaned up some duplicate fixtures.
=> Better UX for tech time off / backfill; refactor Flask app gen

.pre-commit-config.yaml, README.md, docs/qa.md, protohaven_api/commands/development.py, protohaven_api/commands/maintenance.py, protohaven_api/handlers/admin.py, protohaven_api/integrations/neon.py, protohaven_api/scripts/cronicle_qa_tests.py, protohaven_api/scripts/webhook_qa_tests.py, shell.nix, svelte/src/routes/events/+page.svelte, wordpress/protohaven-airtable-grid/src/render.php
* Improve integration testing
* Update QA/readme steps
* Adapt to Neon clearance code schema change
=> Post-deploy fixes

protohaven_api/automation/maintenance/manager.py, protohaven_api/automation/maintenance/manager_test.py, protohaven_api/commands/maintenance.py, protohaven_api/commands/maintenance_test.py, protohaven_api/integrations/comms_test.py
Also moves some of the logic back to the CLI command, so that exceptions are better handled.
=> Improve resilience of maintenance task creation, w/ discord notifications

svelte/src/lib/events/reservations.svelte, svelte/src/lib/techs/assignments.svelte, svelte/src/lib/techs/shifts.svelte, svelte/src/routes/techs/+page.svelte
Also rename /events "Reservations" section to "Today's Reservations" lack of a date caused confusion in the past.
=> Add wiki link and bold current day data in /techs

.gitignore, bookstack/README.md, bookstack/custom_head_content.html, bookstack/docker-compose.yaml, bookstack/theme/approvals.php, bookstack/theme/approvals_test.php, bookstack/theme/backups.php, bookstack/theme/functions.php, bookstack/theme/oauth.php, bookstack/theme/oauth_test.php, bookstack/theme/tool_maintenance_history.php, docs/qa.md
Scrubbed all secrets and moved bookstack out of the server config repo - intent to make it more easily accessed to change/update without providing access to server secrets.
=> Add bookstack custom logical theme

protohaven_api/integrations/wyze.py, requirements.txt, shell.nix
See https://github.com/shauntarves/wyze-sdk/issues/193
=> Tweak wyze SDK fork to properly support getting door sensor state

config.yaml, protohaven_api/automation/classes/scheduler.py, protohaven_api/automation/classes/scheduler_test.py, protohaven_api/commands/development.py, protohaven_api/commands/development_test.py, protohaven_api/handlers/techs_test.py, protohaven_api/integrations/airtable.py, protohaven_api/integrations/data/dev_neon.py, protohaven_api/integrations/data/dev_neon_test.py, svelte/src/lib/dashboard/calendar.svelte
Also includes a basic test of `generate_env` which was untested and caused an error on the instructor dashboard during development.
=> Fix DST bug; rm techs_time_off tbl; sanitize gen_mock_data

docs/qa.md, protohaven_api/automation/classes/scheduler.py, protohaven_api/automation/classes/scheduler_test.py, protohaven_api/integrations/neon.py, protohaven_api/integrations/neon_test.py, svelte/src/routes/techs/+page.svelte
Also some tweaks to the QA doc as part of rollout QA
=> Instructor availability fix; speed up fuzzy member search

protohaven_api/commands/finances.py, protohaven_api/commands/finances_test.py, protohaven_api/integrations/comms_test.py, protohaven_api/integrations/templates/donation_requests.jinja2, protohaven_api/integrations/templates/volunteer_refresh_summary.jinja2
Also add a link to asana for donation requests summary message
=> Add volunteer membership refresh cli command

svelte/src/lib/techs/techs_list.svelte
=> Make sort dropdown appear for non-logged in users on /techs#techs

protohaven_api/handlers/admin.py, protohaven_api/handlers/admin_test.py
=> notify discord with successful or failed clearance updates

protohaven_api/automation/classes/scheduler_test.py, protohaven_api/commands/classes.py, protohaven_api/commands/classes_test.py, protohaven_api/commands/reservations.py, protohaven_api/handlers/techs.py, protohaven_api/handlers/techs_test.py, protohaven_api/integrations/data/dev_booked.py, protohaven_api/integrations/data/dev_neon.py, protohaven_api/integrations/neon_base.py
=> Harden class creation/pricing/reservation, make more dev env friendly

docs/qa.md, protohaven_api/automation/membership/clearances.py, protohaven_api/handlers/admin.py, protohaven_api/handlers/admin_test.py, protohaven_api/integrations/airtable_base.py
Issue found during staging QA - previously full removal of clearances was skipped due to faulty logic. Also added more info to the discord message.
=> Fix admin clearance changing

protohaven_api/automation/maintenance/manager.py, protohaven_api/commands/forwarding.py, protohaven_api/commands/forwarding_test.py, protohaven_api/commands/maintenance.py, protohaven_api/commands/maintenance_test.py, protohaven_api/integrations/comms_test.py, protohaven_api/integrations/tasks.py, protohaven_api/integrations/tasks_test.py, protohaven_api/integrations/templates/class_proposals.jinja2, protohaven_api/integrations/templates/stale_purchase_requests.jinja2, protohaven_api/integrations/templates/tech_leads_maintenance_status.jinja2, protohaven_api/scripts/cronicle_qa_tests.py
These were determined to be neither essential nor nice-to-have by the various leads
=> Remove unused reminder/alerting CLI commands

config.yaml, protohaven_api/integrations/data/dev_neon.py
Allows for editing and inspection of raw data for dev environment when working with Neon
=> Switch to nocodb for fake neon

config.yaml, protohaven_api/automation/classes/builder.py, protohaven_api/automation/classes/builder_test.py, protohaven_api/automation/classes/scheduler.py, protohaven_api/automation/classes/scheduler_test.py, protohaven_api/commands/classes.py, protohaven_api/commands/classes_test.py, protohaven_api/handlers/instructor.py, protohaven_api/handlers/techs_test.py, protohaven_api/integrations/airtable.py, protohaven_api/integrations/airtable_base.py, protohaven_api/integrations/data/connector.py, protohaven_api/integrations/data/dev_connector.py, protohaven_api/integrations/data/dev_neon.py, protohaven_api/integrations/neon_base.py, svelte/src/lib/dashboard/calendar.svelte, svelte/src/lib/dashboard/class_card.svelte, svelte/src/lib/dashboard/class_details.svelte, svelte/src/lib/dashboard/profile.svelte, svelte/src/lib/dashboard/scheduler.svelte, svelte/src/lib/events/classes.svelte
* Update nocodb integration to auto-link records for fields which are references to other tables
* Properly escape URLs in techs dashboard to account for email sub-addressing (`asdf+substring@ghjk.com`)
* User-auth once at the start of `post_classes_to_neon` CLI command, to reduce likelihood of auth failure
* Don't treat single event creation failure as overall failure when pushing classes
* Send a discord message when failing to push classes
=> Harden class pusher, fix nocodb record linking in dev

protohaven_api/commands/maintenance.py, protohaven_api/integrations/templates/tech_daily_tasks.jinja2
=> add techs on shift to maintenance report

protohaven_api/commands/maintenance.py, protohaven_api/commands/maintenance_test.py, protohaven_api/integrations/comms_test.py, protohaven_api/integrations/tasks.py, protohaven_api/integrations/templates/tech_daily_tasks.jinja2
Includes some testing & reliability improvements, plus regenerated salutations and closings
#225
=> @mention techs on shift when generating maintenance tasks

protohaven_api/handlers/instructor.py, protohaven_api/handlers/instructor_test.py, svelte/src/lib/dashboard/calendar_edit.svelte
Adds client- and server-side validation to dates to ensure they're not swapped around. Also adds unit test and fixes a few bugs caught from testing.
Closes #240
=> Prevent malformed availability in instructor dashboard

svelte/src/lib/techs/members.svelte
=> Deduplicate sign ins on /techs#members

docs/qa.md, protohaven_api/commands/clearances.py, protohaven_api/commands/finances.py, protohaven_api/handlers/techs.py, protohaven_api/handlers/techs_test.py, protohaven_api/scripts/cronicle_qa_tests.py, svelte/src/lib/techs/members.svelte
Also fixes a bug with refreshing volunteer memberships
=> /techs: allow viewing front desk sign ins by date

protohaven_api/cli.py, protohaven_api/commands/maintenance.py, protohaven_api/integrations/comms.py, protohaven_api/integrations/discord_bot.py
Adds case-insensitive lookups, includes `_` and `.` punctuation in usernames, and actually resolves @mentions in discord message contents to particular users.
This required lengthening the startup delay before discord comes online for CLI commands, to allow for time to fetch user info.
=> Fix @mentions in tech maintenance tasks Discord messages

config.yaml, protohaven_api/automation/classes/scheduler.py, protohaven_api/automation/classes/scheduler_test.py, protohaven_api/automation/classes/validation.py, protohaven_api/automation/classes/validation_test.py, protohaven_api/cli.py, protohaven_api/handlers/instructor.py, protohaven_api/handlers/instructor_test.py, protohaven_api/integrations/airtable.py, protohaven_api/integrations/data/dev_booked.py, svelte/src/lib/api.ts, svelte/src/lib/dashboard/calendar.svelte
Makes the scheduler and instructor dashboard UI aware of what reservations are configured in Booked. This should partially mitigate conflicts between manually-scheduled events, member reservations, and recurring classes.
=> Reservation aware scheduling

protohaven_api/automation/membership/sign_in.py
=> added membership deferral check based on date

protohaven_api/automation/techs/techs.py, protohaven_api/automation/techs/techs_test.py, protohaven_api/commands/forwarding.py, protohaven_api/commands/forwarding_test.py, protohaven_api/integrations/airtable.py
=> Fix holidays not being respected when sending shift alearts

protohaven_api/automation/classes/events.py, protohaven_api/integrations/data/dev_neon.py, wordpress/protohaven-events/protohaven-events.php
The `$PH_NEON_TOKEN_OPTION_ID` was never registered in settings, so it was not settable in wordpress.
=> Fix WP events plugin setting; Improve dev handling / logging for WP events
